version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: |
          export PACKAGE_VERSION=v$(node -pe "require('./package.json').version")
          git config credential.helper 'cache --timeout=120'
          git config user.email "sam.mccord@protonmail.com"
          git config user.name "sammccord"
          git add .
          git commit --allow-empty -m "$PACKAGE_VERSION"
          git tag $PACKAGE_VERSION
          # Push quietly to prevent showing the token in log
          git push -q https://${GITHUB_TOKEN}@github.com/sammccord/react-native-navigation-experimental-compat.git $PACKAGE_VERSION
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master